name: card_wallet_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  json_serializable: ^6.2.0
  json_annotation: ^4.5.0


  shared_preferences: ^2.0.15

  flutter_colorpicker: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/card_logo.png
    - assets/images/avatar.jpg
    - assets/images/mastercard_logo.png
    - assets/images/visa_logo.png

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/orbitron-bold.ttf
          weight: 800
        - asset: assets/fonts/orbitron/orbitron-medium.ttf
          weight: 500
        - asset: assets/fonts/orbitron/orbitron-regular.ttf
          weight: 400
        - asset: assets/fonts/orbitron/orbitron-semiBold.ttf
          weight: 600

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
