name: messenger_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  firebase_auth: ^3.3.18



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/label.png
    - assets/images/start_call_image.png
    - assets/images/start_message_image.png
    - assets/images/avatars/0.jpg
    - assets/images/avatars/1.jpg
    - assets/images/avatars/2.jpg
    - assets/images/avatars/3.jpg
    - assets/images/avatars/4.jpg
    - assets/images/avatars/5.jpg
    - assets/images/avatars/6.jpg
    - assets/images/avatars/7.jpg
    - assets/images/avatars/8.jpg
    - assets/images/avatars/9.jpg
    - assets/images/avatars/10.jpg
    - assets/images/avatars/11.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900