name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  provider: ^6.0.2
  geolocator: ^8.2.0
  percent_indicator: ^4.0.0
  intl: ^0.17.0
  http: ^0.13.4
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/start_icon.png
    - assets/images/welcome_images/night.png
    - assets/images/welcome_images/sun.png
    - assets/images/welcome_images/rain.png
    - assets/images/welcome_images/sun_cloud.png
    - assets/images/common_weather_icons/humidity.png
    - assets/images/common_weather_icons/pressure.png
    - assets/images/common_weather_icons/wind_direction.png
    - assets/images/common_weather_icons/sunset.png
    - assets/images/common_weather_icons/sun.png
    - assets/images/common_weather_icons/wind.png
    - assets/images/common_weather_icons/day_temp.png
    - assets/images/common_weather_icons/night_temp.png
    - assets/images/common_weather_icons/max_temp.png
    - assets/images/common_weather_icons/min_temp.png
    - assets/images/common_weather_icons/cloud.png
    - assets/images/common_weather_icons/temp_high.png
    - assets/images/common_weather_icons/temp_quarter.png
    - assets/images/common_weather_icons/temp_empty.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
