name: weather_app_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  syncfusion_flutter_calendar: ^20.1.52
  provider: ^6.0.2
  geolocator: ^8.2.0
  percent_indicator: ^4.0.0
  intl: ^0.17.0
  http: ^0.13.4
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/start_icon.png
    - assets/images/welcome_images/night.png
    - assets/images/welcome_images/sun.png
    - assets/images/welcome_images/rain.png
    - assets/images/welcome_images/sun_cloud.png
    - assets/images/common_weather_icons/humidity.png
    - assets/images/common_weather_icons/pressure.png
    - assets/images/common_weather_icons/wind_direction.png
    - assets/images/common_weather_icons/sunset.png
    - assets/images/common_weather_icons/sun.png
    - assets/images/common_weather_icons/wind.png
    - assets/images/common_weather_icons/day_temp.png
    - assets/images/common_weather_icons/night_temp.png
    - assets/images/common_weather_icons/max_temp.png
    - assets/images/common_weather_icons/min_temp.png
    - assets/images/common_weather_icons/cloud.png
    - assets/images/common_weather_icons/temp_high.png
    - assets/images/common_weather_icons/temp_quarter.png
    - assets/images/common_weather_icons/temp_empty.png

